/* eslint-disable */
/**
 * GENERATED FILE — DO NOT EDIT.
 *
 * Produced from api/openapi.json by `npm run clients:generate` in api/.
 * Editing it makes the client disagree with the API again, which is the exact
 * failure it exists to prevent: 26 hand-transcribed types drifted silently
 * because nothing compared them to anything.
 *
 * To change a type here, change the API's DTO or response class, run
 * `npm run openapi:generate` then `npm run clients:generate` in api/, and
 * commit all three files together.
 */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/assets/programs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Assets_programs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/programs/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Assets_program"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/registry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Assets_registry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Audit_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Audit_verify"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Auth_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Auth_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Dashboard_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Health_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investor/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Investor_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investor/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Investor_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investor/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Investor_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investor/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Investor_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kyc/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Kyc_list"];
        put?: never;
        post: operations["Kyc_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kyc/cases/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Kyc_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kyc/cases/{id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Kyc_review"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kyc/cases/{id}/screen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Kyc_screen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kyc/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Kyc_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/passports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Passports_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/passports/{passportId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Passports_byId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/por/attestations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @deprecated */
        get: operations["ProofOfReserves_list"];
        put?: never;
        /** @deprecated */
        post: operations["ProofOfReserves_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/por/attestations/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @deprecated */
        post: operations["ProofOfReserves_publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/por/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @deprecated */
        get: operations["ProofOfReserves_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proof-of-reserves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @deprecated */
        get: operations["Sensitive_reserves"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/purchase/disclosure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @deprecated */
        get: operations["Purchase_disclosure"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/purchase/intents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @deprecated */
        get: operations["Purchase_list"];
        put?: never;
        /** @deprecated */
        post: operations["Purchase_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/purchase/intents/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @deprecated */
        get: operations["Purchase_mine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/purchase/intents/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @deprecated */
        post: operations["Purchase_approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/purchase/intents/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @deprecated */
        post: operations["Purchase_reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/purchase/intents/{id}/settle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @deprecated */
        post: operations["Purchase_settle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/redemption": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @deprecated */
        post: operations["Sensitive_redemption"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/redemption/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @deprecated */
        get: operations["Redemption_list"];
        put?: never;
        /** @deprecated */
        post: operations["Redemption_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/redemption/requests/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @deprecated */
        get: operations["Redemption_mine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/redemption/requests/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @deprecated */
        post: operations["Redemption_approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/redemption/requests/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @deprecated */
        post: operations["Redemption_reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/redemption/requests/{id}/settle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @deprecated */
        post: operations["Redemption_settle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tokenomics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Tokenomics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/waitlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Waitlist_list"];
        put?: never;
        post: operations["Waitlist_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/waitlist/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Waitlist_count"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @deprecated */
        get: operations["Wallet_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wallet/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @deprecated */
        post: operations["Wallet_link"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wallet/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @deprecated */
        get: operations["Wallet_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wallet/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @deprecated */
        post: operations["Wallet_revoke"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AssetProgramDetail: {
            /** @description Short program code, e.g. the copper or nickel program. */
            code: string;
            /** Format: date-time */
            createdAt: string;
            description: string | null;
            id: string;
            metal: string;
            name: string;
            /** @description Illustrative until supporting evidence is published. */
            purity: string;
            records: components["schemas"]["AssetRecordSummary"][];
            status: string;
            /** Format: date-time */
            updatedAt: string;
        };
        AssetProgramSummary: {
            /** @description Short program code, e.g. the copper or nickel program. */
            code: string;
            /** Format: date-time */
            createdAt: string;
            description: string | null;
            id: string;
            metal: string;
            name: string;
            /** @description Illustrative until supporting evidence is published. */
            purity: string;
            status: string;
            /** Format: date-time */
            updatedAt: string;
        };
        AssetRecordSummary: {
            assetId: string;
            batch: string | null;
            /** Format: date-time */
            createdAt: string;
            id: string;
            programId: string;
            status: string;
            /** Format: date-time */
            updatedAt: string;
            /** @description Illustrative. No published weight is evidence-backed yet. */
            weightKg?: number | null;
        };
        AssetRecordWithProgram: {
            assetId: string;
            batch: string | null;
            /** Format: date-time */
            createdAt: string;
            id: string;
            program: components["schemas"]["AssetProgramSummary"];
            programId: string;
            status: string;
            /** Format: date-time */
            updatedAt: string;
            /** @description Illustrative. No published weight is evidence-backed yet. */
            weightKg?: number | null;
        };
        AuditEventResponse: {
            action: string;
            /** @description PII. `[PII_REDACTED]` on a rejected unauthenticated attempt. */
            actorEmail: string | null;
            actorId: string | null;
            actorRole: string | null;
            /** Format: date-time */
            createdAt: string;
            hash: string | null;
            id: string;
            ipAddress: string | null;
            /** @description Request body after redaction: secrets become [REDACTED], PII fields become [PII_REDACTED]. Free-form by nature — this is the one response field a generated client cannot narrow. */
            metadata?: {
                [key: string]: unknown;
            } | null;
            prevHash: string | null;
            resourceId: string | null;
            resourceType: string | null;
            /** @description Monotonic. The hash chain is ordered by this. */
            sequence: number;
            userAgent: string | null;
        };
        AuditListResponse: {
            events: components["schemas"]["AuditEventResponse"][];
            /** @description Total matching the filter, not the page size. */
            total: number;
        };
        AuthLoginResult: {
            /** @description Admin-domain JWT. Not accepted by any investor route. */
            accessToken: string;
            user: components["schemas"]["AuthUser"];
        };
        AuthMe: {
            email: string;
            /** @enum {string} */
            role: "ADMIN" | "COMPLIANCE" | "VIEWER";
            service?: boolean;
            sub?: string;
        };
        AuthUser: {
            email: string;
            id: string;
            /** @enum {string} */
            role: "ADMIN" | "COMPLIANCE" | "VIEWER";
        };
        ChainVerificationResponse: {
            /** @description Present only when `valid` is false. Absent, not null, on a good chain. */
            firstBrokenSequence?: number;
            totalEvents: number;
            valid: boolean;
        };
        CreateAttestationDto: {
            circulatingSupply: number;
            method: string;
            notes?: string;
            periodEnd: string;
            periodStart: string;
            programCode: string;
            verifiedReserve: number;
        };
        CreateKycCaseDto: {
            country: string;
            email?: string;
            legalName: string;
            /** @enum {string} */
            subjectType: "person" | "entity";
        };
        CreatePurchaseDto: {
            programCode: string;
            quoteCurrency?: string;
            tokenAmount: number;
        };
        CreateRedemptionDto: {
            amount: number;
            note?: string;
            programCode: string;
        };
        CreateWaitlistDto: {
            /**
             * @description Must be exactly true.
             * @enum {boolean}
             */
            consent: true;
            email: string;
            fullName: string;
            interest?: string;
            /** @enum {string} */
            investorType: "institution" | "investor" | "partner" | "other";
            locale?: string;
            organization?: string;
        };
        DashboardActivityRow: {
            assetId: string;
            /** @description Program NAME, not code — the service maps `r.program.name`. */
            program: string;
            status: string;
            /** Format: date-time */
            updatedAt: string;
        };
        DashboardRegistrationCount: {
            count: number;
            /** @enum {string} */
            type: "institution" | "investor" | "partner" | "other";
        };
        DashboardStats: {
            /** @description The five most recently updated records. */
            recentActivity: components["schemas"]["DashboardActivityRow"][];
            registrationsByType: components["schemas"]["DashboardRegistrationCount"][];
            totals: components["schemas"]["DashboardTotals"];
        };
        DashboardTotals: {
            passportsIssued: number;
            programs: number;
            records: number;
            waitlist: number;
        };
        HealthResponse: {
            /**
             * @description Result of `SELECT 1` against the API database.
             * @enum {string}
             */
            db: "up" | "down";
            /** @enum {string} */
            status: "ok";
            /** Format: date-time */
            timestamp: string;
        };
        InvestorAuthResult: {
            /** @description Investor-domain JWT (typ=investor). Not accepted by any admin route. */
            accessToken: string;
            investor: components["schemas"]["InvestorPublic"];
        };
        InvestorKycSummary: {
            /** @enum {string} */
            riskLevel: "low" | "medium" | "high" | "unrated";
            /** @description Never a real screening result. `not_screened` when nothing ran, `clear_stub` when the illustrative screener did. */
            sanctions: string;
            /**
             * @description `not_started` is synthesised when no case exists; the other values come from the case row.
             * @enum {string}
             */
            status: "not_started" | "pending" | "in_review" | "approved" | "rejected";
        };
        InvestorProgramSummary: {
            code: string;
            metal: string;
            name: string;
            purity: string;
            status: string;
        };
        InvestorPublic: {
            email: string;
            fullName: string;
            /** @description Null when the caller has a valid token but no investor row — `status` falls back to an email-only profile rather than 404ing. */
            id: string | null;
            /** Format: date-time */
            memberSince?: string | null;
        };
        InvestorStatus: {
            kyc: components["schemas"]["InvestorKycSummary"];
            profile: components["schemas"]["InvestorPublic"];
            programs: components["schemas"]["InvestorProgramSummary"][];
            waitlist: components["schemas"]["InvestorWaitlistSummary"] | null;
        };
        InvestorWaitlistSummary: {
            interest: string | null;
            investorType: string;
            /** Format: date-time */
            joinedAt: string;
            organization: string | null;
        };
        KycCaseDetail: {
            /** @description ISO 3166-1 alpha-2. */
            country: string;
            /** Format: date-time */
            createdAt: string;
            /** @description PII. Present on this role-guarded detail route only; the case list omits it (invariant 23). */
            email?: string | null;
            id: string;
            legalName: string;
            notes?: string | null;
            /** Format: date-time */
            reviewedAt?: string | null;
            reviewedBy?: string | null;
            /** @enum {string|null} */
            riskLevel?: "low" | "medium" | "high" | "unrated" | null;
            /** @description Persisted screening outcome. `clear_stub` is written by the illustrative screener and is not a real screening result. Null means never screened. */
            sanctions?: string | null;
            /** @enum {string} */
            status: "pending" | "in_review" | "approved" | "rejected";
            /** @enum {string} */
            subjectType: "person" | "entity";
            /** Format: date-time */
            updatedAt: string;
        };
        KycCaseListItem: {
            /** @description ISO 3166-1 alpha-2. */
            country: string;
            /** Format: date-time */
            createdAt: string;
            id: string;
            legalName: string;
            notes?: string | null;
            /** Format: date-time */
            reviewedAt?: string | null;
            reviewedBy?: string | null;
            /** @enum {string|null} */
            riskLevel?: "low" | "medium" | "high" | "unrated" | null;
            /** @description Persisted screening outcome. `clear_stub` is written by the illustrative screener and is not a real screening result. Null means never screened. */
            sanctions?: string | null;
            /** @enum {string} */
            status: "pending" | "in_review" | "approved" | "rejected";
            /** @enum {string} */
            subjectType: "person" | "entity";
            /** Format: date-time */
            updatedAt: string;
        };
        KycScreenResult: {
            caseId: string;
            note: string;
            /**
             * @description Always `stub`. No provider is called.
             * @enum {string}
             */
            provider: "stub";
            /**
             * @description Always `clear`. Not a screening result.
             * @enum {string}
             */
            result: "clear";
            /** Format: date-time */
            screenedAt: string;
        };
        KycStats: {
            byStatus: components["schemas"]["KycStatusCount"][];
            total: number;
        };
        KycStatusCount: {
            count: number;
            /** @enum {string} */
            status: "pending" | "in_review" | "approved" | "rejected";
        };
        LinkWalletDto: {
            address: string;
            /** @enum {number} */
            chainId?: 11155111;
        };
        LoginDto: {
            email: string;
            password: string;
        };
        LoginInvestorDto: {
            email: string;
            password: string;
        };
        PassportResponse: {
            assetRecord: components["schemas"]["AssetRecordWithProgram"];
            assetRecordId: string;
            /** Format: date-time */
            createdAt: string;
            id: string;
            /** Format: date-time */
            issuedAt: string | null;
            passportId: string;
            purity: string | null;
            status: string;
            /** @description Always `Illustrative` until a real template is authorised. */
            template: string;
        };
        RegisterInvestorDto: {
            email: string;
            fullName: string;
            password: string;
        };
        RejectPurchaseDto: {
            reason: string;
        };
        RejectRedemptionDto: {
            reason: string;
        };
        ReviewKycCaseDto: {
            notes?: string;
            /** @enum {string} */
            riskLevel?: "low" | "medium" | "high" | "unrated";
            /** @enum {string} */
            status: "pending" | "in_review" | "approved" | "rejected";
        };
        SettlePurchaseDto: {
            txRef?: string;
        };
        SettleRedemptionDto: {
            txRef?: string;
        };
        TokenomicsAllocation: {
            bucket: string;
            pct: number;
        };
        TokenomicsResponse: {
            allocations: components["schemas"]["TokenomicsAllocation"][];
            /** @description Illustrative. Not a committed supply. */
            capIllustrative: string;
            note: string;
            /** @description Illustrative. Not a committed ratio. */
            reserveRatio: string;
            symbol: string;
            transferFee: string;
        };
        WaitlistCount: {
            count: number;
        };
        WaitlistCreated: {
            id: string;
            /** @enum {boolean} */
            ok: true;
        };
        WaitlistEntryResponse: {
            consent: boolean;
            /** Format: date-time */
            createdAt: string;
            /** @description PII. */
            email: string;
            /** @description PII. */
            fullName: string;
            id: string;
            interest: string | null;
            /** @enum {string} */
            investorType: "institution" | "investor" | "partner" | "other";
            /** @enum {string} */
            locale: "en" | "es" | "it";
            /** @description PII. */
            organization: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Assets_programs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetProgramSummary"][];
                };
            };
        };
    };
    Assets_program: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetProgramDetail"];
                };
            };
        };
    };
    Assets_registry: {
        parameters: {
            query: {
                take: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetRecordWithProgram"][];
                };
            };
        };
    };
    Audit_list: {
        parameters: {
            query: {
                skip: string;
                take: string;
                actorId: string;
                action: string;
                resourceType: string;
                fromDate: string;
                toDate: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditListResponse"];
                };
            };
        };
    };
    Audit_verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChainVerificationResponse"];
                };
            };
        };
    };
    Auth_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthLoginResult"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthLoginResult"];
                };
            };
        };
    };
    Auth_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMe"];
                };
            };
        };
    };
    Dashboard_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardStats"];
                };
            };
        };
    };
    Health_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    Investor_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInvestorDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestorAuthResult"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestorAuthResult"];
                };
            };
        };
    };
    Investor_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestorPublic"];
                };
            };
        };
    };
    Investor_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterInvestorDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestorAuthResult"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestorAuthResult"];
                };
            };
        };
    };
    Investor_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestorStatus"];
                };
            };
        };
    };
    Kyc_list: {
        parameters: {
            query: {
                take: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KycCaseListItem"][];
                };
            };
        };
    };
    Kyc_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateKycCaseDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KycCaseDetail"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KycCaseDetail"];
                };
            };
        };
    };
    Kyc_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KycCaseDetail"];
                };
            };
        };
    };
    Kyc_review: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewKycCaseDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KycCaseDetail"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KycCaseDetail"];
                };
            };
        };
    };
    Kyc_screen: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KycScreenResult"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KycScreenResult"];
                };
            };
        };
    };
    Kyc_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KycStats"];
                };
            };
        };
    };
    Passports_list: {
        parameters: {
            query: {
                take: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PassportResponse"][];
                };
            };
        };
    };
    Passports_byId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                passportId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PassportResponse"];
                };
            };
        };
    };
    ProofOfReserves_list: {
        parameters: {
            query: {
                take: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description INACTIVE (P11). Gated by PROOF_OF_RESERVES_ENABLED; with the flag on the service still refuses. Requires written authorization before it does anything. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProofOfReserves_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAttestationDto"];
            };
        };
        responses: {
            /** @description INACTIVE (P11). Gated by PROOF_OF_RESERVES_ENABLED; with the flag on the service still refuses. Requires written authorization before it does anything. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProofOfReserves_publish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description INACTIVE (P11). Gated by PROOF_OF_RESERVES_ENABLED; with the flag on the service still refuses. Requires written authorization before it does anything. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProofOfReserves_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description INACTIVE (P11). Gated by PROOF_OF_RESERVES_ENABLED; with the flag on the service still refuses. Requires written authorization before it does anything. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Sensitive_reserves: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description INACTIVE (P11/P12). Refuses unconditionally. Requires written authorization before it does anything. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Purchase_disclosure: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description INACTIVE (P14). Gated by PURCHASE_ENABLED; with the flag on the service still refuses. Requires written authorization before it does anything. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Purchase_list: {
        parameters: {
            query: {
                status: string;
                take: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description INACTIVE (P14). Gated by PURCHASE_ENABLED; with the flag on the service still refuses. Requires written authorization before it does anything. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Purchase_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePurchaseDto"];
            };
        };
        responses: {
            /** @description INACTIVE (P14). Gated by PURCHASE_ENABLED; with the flag on the service still refuses. Requires written authorization before it does anything. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Purchase_mine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description INACTIVE (P14). Gated by PURCHASE_ENABLED; with the flag on the service still refuses. Requires written authorization before it does anything. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Purchase_approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description INACTIVE (P14). Gated by PURCHASE_ENABLED; with the flag on the service still refuses. Requires written authorization before it does anything. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Purchase_reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectPurchaseDto"];
            };
        };
        responses: {
            /** @description INACTIVE (P14). Gated by PURCHASE_ENABLED; with the flag on the service still refuses. Requires written authorization before it does anything. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Purchase_settle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettlePurchaseDto"];
            };
        };
        responses: {
            /** @description INACTIVE (P14). Gated by PURCHASE_ENABLED; with the flag on the service still refuses. Requires written authorization before it does anything. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Sensitive_redemption: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description INACTIVE (P11/P12). Refuses unconditionally. Requires written authorization before it does anything. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Redemption_list: {
        parameters: {
            query: {
                status: string;
                take: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description INACTIVE (P12). Gated by REDEMPTION_ENABLED; with the flag on the service still refuses. Requires written authorization before it does anything. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Redemption_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRedemptionDto"];
            };
        };
        responses: {
            /** @description INACTIVE (P12). Gated by REDEMPTION_ENABLED; with the flag on the service still refuses. Requires written authorization before it does anything. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Redemption_mine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description INACTIVE (P12). Gated by REDEMPTION_ENABLED; with the flag on the service still refuses. Requires written authorization before it does anything. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Redemption_approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description INACTIVE (P12). Gated by REDEMPTION_ENABLED; with the flag on the service still refuses. Requires written authorization before it does anything. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Redemption_reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectRedemptionDto"];
            };
        };
        responses: {
            /** @description INACTIVE (P12). Gated by REDEMPTION_ENABLED; with the flag on the service still refuses. Requires written authorization before it does anything. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Redemption_settle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettleRedemptionDto"];
            };
        };
        responses: {
            /** @description INACTIVE (P12). Gated by REDEMPTION_ENABLED; with the flag on the service still refuses. Requires written authorization before it does anything. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Tokenomics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenomicsResponse"];
                };
            };
        };
    };
    Waitlist_list: {
        parameters: {
            query: {
                take: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaitlistEntryResponse"][];
                };
            };
        };
    };
    Waitlist_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWaitlistDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaitlistCreated"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaitlistCreated"];
                };
            };
        };
    };
    Waitlist_count: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaitlistCount"];
                };
            };
        };
    };
    Wallet_list: {
        parameters: {
            query: {
                take: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description INACTIVE (P13). Gated by WALLET_ENABLED; with the flag on the service still refuses. Requires written authorization before it does anything. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Wallet_link: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkWalletDto"];
            };
        };
        responses: {
            /** @description INACTIVE (P13). Gated by WALLET_ENABLED; with the flag on the service still refuses. Requires written authorization before it does anything. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Wallet_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description INACTIVE (P13). Gated by WALLET_ENABLED; with the flag on the service still refuses. Requires written authorization before it does anything. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Wallet_revoke: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description INACTIVE (P13). Gated by WALLET_ENABLED; with the flag on the service still refuses. Requires written authorization before it does anything. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
